name: Testing

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  pytest:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v4.2.2"
      - name: Setup Python
        uses: "actions/setup-python@v5.4.0"
        with:
          python-version-file: ".python-version"
      - name: Install requirements
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip install -r requirements_test.txt
      - name: Tests suite
        run: |
          pytest \
            --timeout=9 \
            --durations=10 \
            --cov-fail-under=90 \
            -n auto \
            -p no:sugar \
            tests
